modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/sokratis12GR/TheDragonLib/issues"
[[mods]]
modId="thedragonlib"
version="1.14.4-7.0.1"
displayName="TheDragonLib"
updateJSONURL="https://github.com/sokratis12GR/TheDragonLib/blob/1.14/thedragonlib-updater.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/thedragonlib"
authors="SoFoDev" #optional
description='''A library for all SoFoDev's Mods'''

[[dependencies.thedragonlib]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.thedragonlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"